#!/usr/bin/env python

import os
import sys
import uvicore
from acme.appstub.package import bootstrap

# Bootstrap the Uvicore application from the console entrypoint
app = bootstrap.Application(is_console=True)()

if __name__ == '__main__':
    try:
        # Get the cli method from the IoC
        cli = uvicore.ioc.make('Console')

        # Instantiate the main asyncclick group
        cli(_anyio_backend='asyncio')

    except KeyboardInterrupt:
        try:
            sys.exit(0)
        except SystemExit:
            os._exit(0)
