[project]
name = "acme-appstub"
version = "0.1.0"
description = "Acme Test App"
authors = [
    {name = "Artisan Smith",email = "smith@example.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"

# Required base dependencies
dependencies = [
<pyproject-uvicore>
]

[tool.poetry]
packages = [
    { include = "acme/appstub" },
]

# poetry install --with test"
[tool.poetry.group.test.dependencies]
pytest = "8.3.*"
pytest-cov = "6.0.*"
pytest-asyncio = "0.25.*"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
